{
	"version": 1655136049,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/finish-sheet0.png",
		"images/startline-sheet0.png",
		"images/car-sheet0.png",
		"images/start-sheet0.png",
		"images/grass-sheet0.png",
		"images/sprite-sheet0.png",
		"images/road2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/barrel-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/road-sheet0.png",
		"images/h-sheet0.png",
		"images/barrier-sheet0.png",
		"images/loosepicture-sheet0.png",
		"images/tree-sheet0.png",
		"images/bush-sheet0.png",
		"images/tiledbackground2.png",
		"images/pond-sheet0.png",
		"images/background-sheet0.png",
		"images/powerup-sheet0.png",
		"images/spike-sheet0.png",
		"media/80's style pixel art music.m4a",
		"media/80's style pixel art music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}